---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 1m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./infrastructure/configs
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 1m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./infrastructure/controllers
  prune: true
  wait: true
