apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    controller:
      enabled: true
    speaker:
      enabled: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: "NoSchedule"
