apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole
  namespace: pihole
spec:
  secretName: pihole
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - pihole.umbos.net
