apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    admin:
      existingSecret: "pihole"
      passwordKey: "admin-password"
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    extraEnvVars:
      TZ: "America/New_York"
    persistentVolumeClaim:
      enabled: true
    serviceWeb:
      type: NodePort
      http:
        nodePort: 39278
      https:
        enabled: false
