apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    replicaCount: 1
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.50.249"
    serviceWeb:
      type: ClusterIP
      https:
        enabled: false
    persistentVolumeClaim:
      enabled: true
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    admin:
      existingSecret: "pihole"
      passwordKey: "admin-password"
    extraEnvVars:
      TZ: "America/New_York"
