apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      chart: pihole
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    admin:
      existingSecret: "pihole"
      passwordKey: "admin-password"
    extraEnvVars:
      TZ: "America/New_York"
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: "192.168.50.249"
    serviceDhcp:
      enabled: false
    serviceWeb:
      https:
        enabled: false
    persistentVolumeClaim:
      enabled: true
